### ISSUE TITLE
Update To The Api 3.17.2 

### ISSUE THREAD

**Issue by ghassankero** [HBIDamian/MOTDShuffle#10]
Can You Update The Api To The 3.17.2 because It Incompatible For My Pocket mine Server :(

**Comment by HBIDamian** [comment]
Unless you are using a version that is not API 3, then it should be fine. 
But if you insist, https://poggit.pmmp.io/r/112950/MOTDShuffle_dev-13.phar.

**Comment by HBIDamian** [comment]
Closing thread
