### ISSUE TITLE
Color Support

### ISSUE THREAD

**Issue by tomw93377** [HBIDamian/MOTDShuffle#6]
Can you add color support please?
Cheers,
tdubz1

**Comment by HBIDamian** [comment]
Use the `§` symbol. 

On Windows, to get this symbol, make sure numlock is on, Hold "Alt" and type `0167` on the number pad
I believe on Android, hold the `&` symbol and you'll find §.

But I will add support for & symbol at some point. I don't know when though, as I am busy.
