### ISSUE TITLE
does not work after MOTD change!

### ISSUE THREAD

**Issue by supercrafter333** [HBIDamian/MOTDShuffle#7]
I only changed the basic MOTD And after that it was no longer possible!

**Comment by HBIDamian** [comment]
I tested the plugin, latest Stable PocketMine https://github.com/pmmp/PocketMine-MP/releases/tag/3.11.7. I have the latest MCWin10 Version 10.
It all seems to work fine for me. 
Perhaps there is an issue with your config.

**Comment by supercrafti-lab** [comment]
no, I have everything set normally it just didn't work after changing the normal MOTD

**Comment by HBIDamian** [comment]
I've tried replicating the issue (based on the limited information you given me due to it being a shitty description tbh) and I can't replicate it. 
It seems to me that its some human error on your side. 

Please send the exact steps you've made to have this issue.

**Comment by supercrafti-lab** [comment]
- MOTDShuffle MOTD changed
- Normal MOTD changed

After this, the Plugin does't works

**Comment by HBIDamian** [comment]
That's not steps. That's just you rephrasing what you just said above. 🤦

**Comment by supercrafti-lab** [comment]
That's how I did it, and after that their plugin stopped working!

However, it was loaded normally, only what it was supposed to do didn't do it!

**Comment by AshiePleb** [comment]
Plugin works fine for me you probably broke something and are blaming the plugin.. maybe try delete the plugins data and see if it fixes.

**Comment by supercrafti-lab** [comment]
The normal MOTD remained and that of her plugin was not displayed!

**Comment by AshiePleb** [comment]
sounds like a personal problem

**Comment by supercrafti-lab** [comment]
Okay, i do this

**Comment by HBIDamian** [comment]
From what I'm told, you possibly used colour codes?

```
#The Ammount of time that you wish for the MOTD Delay.
#This doesn't make the client's query change,
#this effects the ammount of time the server sends the message.
#Default: 100
MOTD Delay: 100

#Here you can set if you want the shuffle on, or off.
#It is required to use quotations. :D
#Default: "off"
MOTD Shuffle: "off"

#The MOTD Messages.
#You can add to as much as you like! 
#Just make sure you copy it correctly. 
MOTD Message:
    - "§l§m§dCosmicCreations §eBeta§r §5Factions"
    - "§l§m§dCosmicCreations §eBeta§r §5PvP"
```

Use the `§` colour code format, and make sure you are encoding it under UTF-8. Most other encoding views it as `Â§lÂ§` and that ends up not working.

**Comment by supercrafti-lab** [comment]
I have deleted the config.
The problem remains!

**Comment by HBIDamian** [comment]
Hang on, do you  have the plugin "CustomAlerts"?

**Comment by supercrafti-lab** [comment]
Yes

**Comment by HBIDamian** [comment]
Thats the issue there unfortunately.
That plugin constantly sets the MOTD even when it's turned off in their config. 
To be able to use MOTDShuffle, you can't use CustomAlerts. 
Feel free to send them an issue saying that they stop plugins like MOTDShuffle from working. 
Sorry about that.

**Comment by supercrafti-lab** [comment]
Oh, thaks
